In [4]:
#Generar un archivo tipo Notebook de Python que contenga el código fuente de varios ejercicios aplicados a los conceptos vistos:
#Uso de librería pandas – leer archivo fifa_eda.csv 
import pandas as pd
import os

os.chdir('/Users/davidherrera/Downloads')
df = pd.read_csv('fifa_eda.csv')

In [5]:
#Visualización de una muestra de 20 líneas. 
#De ser necesario, utilizar el código del ejercicio anterior para no tener que repetir refinamientos de datos
df[0:20]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
5,183277,E. Hazard,27,Belgium,91,91,Chelsea,93000.0,340.0,Right,4.0,4.0,LF,2012,2020-01-01,5.666667,163.0,172100.0
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000.0,420.0,Right,4.0,4.0,RCM,2012,2020-01-01,5.666667,146.0,137400.0
7,176580,L. Suárez,31,Uruguay,91,91,FC Barcelona,80000.0,455.0,Right,5.0,3.0,RS,2014,2021-01-01,6.000000,190.0,164000.0
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000.0,380.0,Right,4.0,3.0,RCB,2005,2020-01-01,6.000000,181.0,104600.0
9,200389,J. Oblak,25,Slovenia,90,93,Atlético Madrid,68000.0,94.0,Right,3.0,1.0,GK,2014,2021-01-01,6.166667,192.0,144500.0
10,188545,R. Lewandowski,29,Poland,90,90,FC Bayern München,77000.0,205.0,Right,4.0,4.0,ST,2014,2021-01-01,6.000000,176.0,127100.0
11,182521,T. Kroos,28,Germany,90,90,Real Madrid,76500.0,355.0,Right,4.0,3.0,LCM,2014,2022-01-01,6.000000,168.0,156800.0
12,182493,D. Godín,32,Uruguay,90,90,Atlético Madrid,44000.0,125.0,Right,3.0,2.0,CB,2010,2019-01-01,6.166667,172.0,90200.0
13,168542,David Silva,32,Spain,90,90,Manchester City,60000.0,285.0,Left,4.0,4.0,LCM,2010,2020-01-01,5.666667,148.0,111000.0
14,215914,N. Kanté,27,France,89,90,Chelsea,63000.0,225.0,Right,3.0,2.0,LDM,2016,2023-01-01,5.500000,159.0,121300.0
15,211110,P. Dybala,24,Argentina,89,94,Juventus,89000.0,205.0,Left,3.0,4.0,LF,2015,2022-01-01,5.833333,165.0,153500.0
16,202126,H. Kane,24,England,89,91,Tottenham Hotspur,83500.0,205.0,Right,3.0,3.0,ST,2010,2024-01-01,6.166667,196.0,160700.0
17,194765,A. Griezmann,27,France,89,90,Atlético Madrid,78000.0,145.0,Left,4.0,4.0,CAM,2014,2023-01-01,5.750000,161.0,165800.0
18,192448,M. ter Stegen,26,Germany,89,92,FC Barcelona,58000.0,240.0,Right,3.0,1.0,GK,2014,2022-01-01,6.166667,187.0,123300.0
19,192119,T. Courtois,26,Belgium,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.0

In [ ]:
#Generar la media, mínimo y máximo de los jugadores en total, y por país (groupby)
mean = df.count().mean()
min = df.count().min()
max = df.count().max()

print(f"Media de jugadores= {mean:.2f}")
print(f"Minima de jugadores= {min:.2f}")
print(f"Maxima de jugadores= {max:.2f}")

Media de jugadores= 18158.22
Minima de jugadores= 17918.00
Maxima de jugadores= 18207.00

In [19]:
#Generar 2 jugadores ficticios con todos los campos del dataset y añadirlos al mismo.  Visualizarlos con .tail().  Correr nuevamente las estadísticas y compararlas.
datos_nuevos = [(246621, 'Dave', 26, 'México', 89, 90, 'Real Madrid', 53500.0, 240.0, 'Left', 4.0, 1.0, 'GK', 2018, '2024-01-01', 6.500000, 212.0, 113700.0),
                (246621, 'Anne', 26, 'México', 89, 90, 'Real Madrid', 53500.0, 240.0, 'Left', 4.0, 1.0, 'GK', 2018, '2024-01-01', 6.500000, 212.0, 113700.0)
                ]

df_dn = pd.DataFrame(datos_nuevos, columns=['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value', 'Wage', 'Preferred Foot', 'International Reputation', 'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height', 'Weight', 'Release Clause'])

In [20]:
df_dn

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,246621,Dave,26,México,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.5,212.0,113700.0
1,246621,Anne,26,México,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.5,212.0,113700.0

In [21]:
df_unido = pd.concat([df, df_dn], axis=0, ignore_index=True)

In [22]:
df_unido.tail(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
18207,246621,Dave,26,México,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.0
18208,246621,Anne,26,México,89,90,Real Madrid,53500.0,240.0,Left,4.0,1.0,GK,2018,2024-01-01,6.500000,212.0,113700.0

In [45]:
#Generar una lambda que añada la zona horaria y la capital del país de nacionalidad
import country_converter as coco

df_unido['CC'] = coco.convert(names=df_unido['Nationality'], to='ISO2', not_found=None)

Wales not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Scotland not found in regex
Scotland not found in regex
Northern Ireland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Wales not found in regex
Scotland not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
Wales not found in regex
Scotland not found in regex
México not found in regex
México not found in regex

In [48]:
import pytz

df_unido['Zona Horaria'] = df_unido['CC'].apply(lambda x:pytz.country_timezones.get(x))

In [52]:
from countryinfo import CountryInfo

def cap(pais):
    if pd.isna(pais):
        return pd.NA   
    try:
        return CountryInfo(pais).capital()
    except:
        return pd.NA

df_unido['Capital'] = df_unido['Nationality'].apply(cap)

In [53]:
df_unido.sample(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,CC,Zona Horaria,Capital
17668,242606,S. Strózik,19,Poland,53,69,Cracovia,130.0,1.0,Right,...,2.0,RM,2016,2021-01-01,5.833333,168.0,257.0,PL,[Europe/Warsaw],Warsaw
2056,236792,T. Souček,23,Czech Republic,75,83,SK Slavia Praha,8500.0,1.0,Right,...,2.0,RDM,2014,2020-01-01,6.333333,190.0,20400.0,CZ,[Europe/Prague],Prague
6975,238938,B. Girth,26,Germany,68,70,Holstein Kiel,1100.0,6.0,Right,...,3.0,ST,2018,2021-01-01,5.916667,181.0,1800.0,DE,"[Europe/Berlin, Europe/Busingen]",Berlin
11950,225253,H. Artarslan,24,Turkey,64,67,Trabzonspor,475.0,5.0,Right,...,2.0,CDM,2012,2020-01-01,6.250000,185.0,986.0,TR,[Europe/Istanbul],Ankara
17322,242723,D. Castro,24,Chile,54,60,Unión La Calera,90.0,1.0,Right,...,2.0,ST,2018,2021-01-01,5.583333,141.0,140.0,CL,"[America/Santiago, America/Coyhaique, America/...",Santiago

In [56]:
#Generar una lambda que en base al potencial, añada una columna “Candidato” o “Next Year”, para el premio para el balón de oro.  Jugadores con más de 85, son candidatos.#

df_unido['Candidato'] = df_unido['Potential'].apply(lambda x:'Yes' if x > 85 else 'No')

In [67]:
df_unido.tail(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,CC,Zona Horaria,Capital,Candidato
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,...,ST,2017,2021-01-01,5.666667,148.0,165.0,GB,[Europe/London],<NA>,No
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,...,RW,2018,2019-01-01,5.833333,154.0,143.0,GB,[Europe/London],<NA>,No
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,...,CM,2018,2019-01-01,5.833333,176.0,165.0,GB,[Europe/London],<NA>,No
18207,246621,Dave,26,México,89,90,Real Madrid,53500.0,240.0,Left,...,GK,2018,2024-01-01,6.500000,212.0,113700.0,México,None,Mexico City,Yes
18208,246621,Anne,26,México,89,90,Real Madrid,53500.0,240.0,Left,...,GK,2018,2024-01-01,6.500000,212.0,113700.0,México,None,Mexico City,Yes